class Sentence < ActiveHash::Base
  self.data = [
    { id: 1, english: 'The girl got a bicycle for Christmas.', japanese: 'その少年はクリスマスに自転車をもらった。', category_id: 1 },
    { id: 2, english: 'I got enough sleep last night.', japanese: '私は昨夜十分に寝た。', category_id: 1 },
    { id: 3, english: 'He got a good education.', japanese: '彼は良い教育を受けた。', category_id: 1 },
    { id: 4, english: 'When I first met the young man, I got a good impression.', japanese: 'その若者に初めて会った時、私は好印象を受けた。', category_id: 1 },
    { id: 5, english: 'Emily got her musical talent from her mother.', japanese: 'エミリーは母親から音楽的才能を受け継いだ。', category_id: 1 },
    { id: 6, english: 'My aunt always gets bread at that bakery.', japanese: '私の叔母はいつもパンをあのパン屋で買う。', category_id: 1 },
    { id: 7, english: 'Get your coat.', japanese: 'コートを取っておいで。', category_id: 1 },
    { id: 8, english: 'Would you get me a glass of water?', japanese: '私に水を1杯いただけますか？', category_id: 1 },
    { id: 9, english: 'Shall I get you a chair?', japanese: '椅子を持ってきましょうか？', category_id: 1 },
    { id: 10, english: 'Where did you get the cold?', japanese: 'どこで風邪をひいたのですか？', category_id: 1 },
    { id: 11, english: 'The teddy bear I got for my fifth birthday is still my treasure.', japanese: '５歳の誕生日にもらったテディベアはいまだに私の宝物です。', category_id: 1 },
    { id: 12, english: 'I feel that I need to get some rest.', japanese: '少し休憩をとる必要があると感じています。', category_id: 1 },
    { id: 13, english: 'Did your sister get her education in Europe?', japanese: 'あなたのお姉さんはヨーロッパで教育を受けたのですか？', category_id: 1 },
    { id: 14, english: 'I got the impression that he was loved by everyone.', japanese: '彼はみんなに愛されているという印象を私は受けました。', category_id: 1 },
    { id: 15, english: 'He got his strong shoulders from his father.', japanese: '彼のがっしりした肩は父親譲りだ。', category_id: 1 },
    { id: 16, english: 'Have you gotten tickets for the concert yet?', japanese: 'コンサートのチケットはもう入手しましたか？', category_id: 1 },
    { id: 17, english: "I'll go get the newspaper.", japanese: '私が新聞を取りに行くよ。', category_id: 1 },
    { id: 18, english: "I'll get you a drink.", japanese: '僕があなたに飲み物を持ってきます。', category_id: 1 },
    { id: 19, english: 'His father got him a job.', japanese: '彼のお父さんが彼に仕事を見つけてくれた。', category_id: 1 },
    { id: 20, english: "Didn't you get the flu from him?", japanese: '彼からインフルエンザをうつされませんでしたか？', category_id: 1 },
    { id: 21, english: "I'm sorry, I didn't get your name.", japanese: 'すみませんが、お名前が聞き取れませんでした。', category_id: 1 },
    { id: 22, english: 'I got a good idea while I was talking a walk this morning.', japanese: '私は今朝散歩中にいい考えが浮かんだ。', category_id: 1 },
    { id: 23, english: 'We got the enemy before they got us.', japanese: '私たちはやられる前に敵をやっつけた。', category_id: 1 },
    { id: 24, english: 'She will soon get a promotion.', japanese: '彼女はまもなく昇進するだろう。', category_id: 1 },
    { id: 25, english: 'My father has gotten a lot of gray hair recently.', japanese: '父は最近白髪がとても増えた。', category_id: 1 },
    { id: 26, english: 'He went to the beach to get a suntan.', japanese: '彼は肌を焼くために浜辺に行った。', category_id: 1 },
    { id: 27, english: 'My room does not get much sunshine.', japanese: '私の部屋は日当たりが良くない。', category_id: 1 },
    { id: 28, english: 'The boxer got a punch on the chin and went down.', japanese: 'そのボクサーは顎にパンチを受けて倒れた。', category_id: 1 },
    { id: 29, english: "The mother tried to get a better look at her son's face.", japanese: 'その母親は息子の顔をもっとよく見ようとした。', category_id: 1 },
    { id: 30, english: "I have to get my wife's consent before getting the car.", japanese: 'その車を買う前に私は妻の同意をえらなければならない。', category_id: 1 },
    { id: 31, english: "Since he didn't get the joke, he couldn't laugh.", japanese: 'そのジョークがわからなかっtので、彼は笑えなかった。', category_id: 1 },
    { id: 32, english: 'Why did you get the idea that she was in love with you?', japanese: '君はなぜ彼女が君に恋をしていると思ったんだい？', category_id: 1 },
    { id: 33, english: 'They will get us unless we get them first.', japanese: '彼らを先にやっつけないと私たちがやられてしまうぞ。', category_id: 1 },
    { id: 34, english: "I haven't gotten a raise for three years.", japanese: '私は三年間昇給していません。', category_id: 1 },
    { id: 35, english: 'I started to get gray hair in my thirties.', japanese: '私は三十代で白髪が出始めた。', category_id: 1 },
    { id: 36, english: 'He asked me where I had gotten a tan.', japanese: '彼はどこで日焼けしたのか私に尋ねた。', category_id: 1 },
    { id: 37, english: "Why don't you go out and get some fresh air?", japanese: '外に出て新鮮な空気を吸ったらどうですか？', category_id: 1 },
    { id: 38, english: 'The soldier got a bullet in his right leg.', japanese: '銃弾が兵士の右脚に当たった。', category_id: 1 },
    { id: 39, english: 'The man got a glimpse of the car.', japanese: 'その男は車をチラリと見た。', category_id: 1 },
    { id: 40, english: "We haven't gotten permission to use this design yet.", japanese: '私たちはこのデザインを使用する許可をまだ取っていません。', category_id: 1 },
    { id: 41, english: 'Have you already gotten full?', japanese: 'もう満腹になりましたか？', category_id: 1 },
    { id: 42, english: 'I hope your mother will get well soon.', japanese: 'あなたのお母さんがすぐ良くなるといいですね。', category_id: 1 },
    { id: 43, english: 'Have you gotten ready for the presentation?', japanese: 'プレゼンの準備はできたかい？', category_id: 1 },
    { id: 44, english: 'I get tired easily these days.', japanese: '最近すぐに疲れる。', category_id: 1 },
    { id: 45, english: 'It is getting warmer every day.', japanese: '毎日、暖かくなっています。', category_id: 1 },
    { id: 46, english: 'The window got broken in the typhoon.', japanese: '台風で窓が割れた。', category_id: 1 },
    { id: 47, english: 'More than five people got injured in the accident.', japanese: '5人以上の人がその事故で怪我をしました。', category_id: 1 },
    { id: 48, english: 'I got dinner ready for all the guests in a great hurry.', japanese: '私は大急ぎで全ての客のために夕食の用意をしました。', category_id: 1 },
    { id: 49, english: 'Have you gotten your homework done yet?', japanese: 'もう宿題はしたのかい？', category_id: 1 },
    { id: 50, english: 'She got her car repaired.', japanese: '彼女は車を修理してもらった。', category_id: 1 },
    { id: 51, english: 'He got his car damaged in the parking lot.', japanese: '彼は駐車場で車を傷つけられた。', category_id: 1 },
    { id: 52, english: 'She got her boyfriend to give up smoking.', japanese: '彼女は彼氏にタバコを辞めさせた。', category_id: 1 },
    { id: 53, english: 'You can eat until you get full.', japanese: '君は満腹になるまで食べてもいいんだよ。', category_id: 1 },
    { id: 54, english: 'You will get much better in a couple of days.', japanese: 'あなたは二、三日で大分良くなるでしょう。', category_id: 1 },
    { id: 55, english: 'Shall we get started now?', japanese: 'さあ始めようか。', category_id: 1 },
    { id: 56, english: 'He have gotten sick of doing the same thing.', japanese: '彼は同じことをするのにうんざりしてしまった。', category_id: 1 },
    { id: 57, english: 'The days are getting longer.', japanese: '日が長くなってきています。', category_id: 1 },
    { id: 58, english: 'Have you ever gotten stung by a bee?', japanese: '蜂に刺されたことはありますか？', category_id: 1 },
    { id: 59, english: 'Do you know how many people got killed in the fire?', japanese: 'その火事で何人亡くなったかあなたは知っていますか？', category_id: 1 },
    { id: 60, english: 'I told her to get the engine started.', japanese: '私は彼女にエンジンをかけるように言った。', category_id: 1 },
    { id: 61, english: 'He promised to get the report finished in a week.', japanese: '彼は報告書を一週間で仕上げると約束した。', category_id: 1 },
    { id: 62, english: 'She got my hair dyed at the hair salon.', japanese: '彼女は美容室で髪を染めてもらいました。', category_id: 1 },
    { id: 63, english: 'Where did you get your wallet stolen?', japanese: 'どこで財布を盗まれましたか？', category_id: 1 },
    { id: 64, english: 'How can we get people to buy our products?', japanese: '私たちはどうやったら人々に商品を買わせることができるだろうか？', category_id: 1 },
    { id: 65, english: 'They got to New York yesterday.', japanese: '彼らは昨日ニューヨークに到着した。', category_id: 1 },
    { id: 66, english: 'Get this chair upstairs.', japanese: 'この椅子を上の階に持っていってください。', category_id: 1 },
    { id: 67, english: 'Going like this will get you nowhere.', japanese: 'こんな風にしていてもあなたはどうにもならないでしょう。', category_id: 1 },
    { id: 68, english: 'Someone got in through the window.', japanese: '誰かが窓から入りました。', category_id: 1 },
    { id: 69, english: 'The train got in on time.', japanese: '電車は時間通りに到着しました。', category_id: 1 },
    { id: 70, english: 'The dog got into the box.', japanese: 'その犬は箱の中に入りました。', category_id: 1 },
    { id: 71, english: "I don't want to get into trouble.", japanese: '面倒なことにはなりたくないです。', category_id: 1 },
    { id: 72, english: 'They got the wild bear into a cage.', japanese: '彼らはその野生の熊を檻に入れました。', category_id: 1 },
    { id: 73, english: 'The man told us to get out.', japanese: 'その男の人は私たちに出ていくように言った。', category_id: 1 },
    { id: 74, english: 'The secret got out.', japanese: 'その秘密は漏れました。', category_id: 1 },
    { id: 75, english: 'What time did you get here?', japanese: '君は何時にここに着いたんですか？', category_id: 1 },
    { id: 76, english: 'That bus will get you to the station.', japanese: 'あのバスに乗ればあなたは駅に行けるだろう。', category_id: 1 },
    { id: 77, english: "Feeling sorry for youself won't get you anywhere.", japanese: '自分を哀れんでいてもどうにもならないですよ。', category_id: 1 },
    { id: 78, english: "Since I didn't have the key, I couldn't get in.", japanese: '鍵を持っていなかったので、中に入れなかった。', category_id: 1 },
    { id: 79, english: 'What time does your plane get in?', japanese: 'あなたの飛行機は何時に到着ですか？', category_id: 1 },
    { id: 80, english: 'I saw him get into a taxi.', japanese: '私は彼がタクシーに乗り込むのを見ました。', category_id: 1 },
    { id: 81, english: 'The man gets into a temper easily.', japanese: 'あの人はすぐに癇癪をおこします。', category_id: 1 },
    { id: 82, english: "I didn't want to get him into trouble.", japanese: '彼を面倒に巻き込みたくなかった。', category_id: 1 },
    { id: 83, english: 'As soon as the elevator doors opened, that old man got out.', japanese: 'エレベーターのドアが開くとすぐにあの老人は外に出ました。', category_id: 1 },
    { id: 84, english: 'If this gets out, we will get into trouble.', japanese: 'もしこれが露見すれば、私たちは困ったことになるでしょう。', category_id: 1 },
    { id: 85, english: 'How did the bear get out of the cage?', japanese: 'その熊はどうやって檻から出たんですか？', category_id: 1 },
    { id: 86, english: 'The excited crowds got out of control.', japanese: '興奮した群衆は抑えが効かなくなっていました。', category_id: 1 },
    { id: 87, english: 'The policeman tole everyone to get down.', japanese: 'その警官はみんなに伏せるように言いました。', category_id: 1 },
    { id: 88, english: 'koalas rarely gets down to the ground.', japanese: 'コアラはめったに地面に下りません。', category_id: 1 },
    { id: 89, english: 'The cat easily got over the fence.', japanese: 'その猫はたやすくフェンスを乗り越えました。', category_id: 1 },
    { id: 90, english: 'She will get over the cold in a couple days.', japanese: '彼女の風邪は二、三日で治るでしょう。', category_id: 1 },
    { id: 91, english: 'The bank robber got away with one million dollars.', japanese: '銀行強盗は100万ドル盗んで逃げました。', category_id: 1 },
    { id: 92, english: 'The boat got across the river.', japanese: 'ボートは川を渡りました。', category_id: 1 },
    { id: 93, english: 'Did your point get across to the students.', japanese: 'あなたの言わんとすることは生徒たちに伝わりましたか？', category_id: 1 },
    { id: 94, english: 'I hope I could get the message across to her.', japanese: 'そのメッセージを彼女に伝えられたのだといいのですが。', category_id: 1 },
    { id: 95, english: 'He wanted to get out of the party as soon as possible.', japanese: '彼はできるだけすぐにパーティーから抜け出したかった。', category_id: 1 },
    { id: 96, english: 'Things are getting out of hand.', japanese: '事態は手に負えなくなりつつあります。', category_id: 1 },
    { id: 97, english: 'The terrorists told the hostages to get down on all fours.', japanese: 'テロリストたちは人質に四つん這いになるように言いました。', category_id: 1 },
    { id: 98, english: "Now it's time to get down to business.", japanese: 'さあ仕事に取り掛かる時間だ。', category_id: 1 },
    { id: 99, english: 'Nobody could get over such a high wall.', japanese: '誰もそんなに高い壁を乗り越えることはできませんでした。', category_id: 1 },
    { id: 100, english: 'It may take his some time to get over the shock.', japanese: '彼がショックから立ち直るにはしばらく時間がかかるかもしれません。', category_id: 1 },
    { id: 101, english: "He couldn't think he can get away with such behavior.", japanese: '彼はこんな行いをしてただで済むと思うべきではありません。', category_id: 1 },
    { id: 102, english: 'Thousands of refugees got across the border to the neighboring country.', japanese: '何千人もの難民が国境を超えて隣国へ入りました。', category_id: 1 },
    { id: 103, english: "My joke didn't get across to the audience.", japanese: '私のジョークは聴衆に伝わらなかった。', category_id: 1 },
    { id: 104, english: 'The professor found it hard to get the nuance of the phrase across to the students.', japanese: '教授はその言い回しのニュアンスを学生たちに伝えるのは難しいと感じました。', category_id: 1 },
    { id: 105, english: 'The incident gave people throughout the world a shock.', japanese: 'その出来事は世界中の人々に衝撃を与えました。', category_id: 2 },
    { id: 106, english: 'The mother gave all her love to her child.', japanese: 'その母親は愛情を全て自分の子供に注ぎました。', category_id: 2 },
    { id: 107, english: 'The president gave a moving speech.', japanese: '大統領は感動的な演説をしました。', category_id: 2 },
    { id: 108, english: 'Shall I give you a ride to the station?', japanese: '駅まで車で送りましょうか？', category_id: 2 },
    { id: 109, english: 'Reading gives me greater pleasure than anything else.', japanese: '私は読書が何よりも楽しいです。', category_id: 2 },
    { id: 110, english: "He gave little attention to his parents' advise.", japanese: '彼は彼の両親の忠告にほとんど注意を払いませんでした。', category_id: 2 },
    { id: 111, english: 'You should not give much trouble to your parents.', japanese: 'あなたは両親にあまり迷惑をかけるべきではないです。', category_id: 2 },
    { id: 112, english: 'She gave a cry at the sight.', japanese: '彼女はその光景に叫び声を上げました。', category_id: 2 },
    { id: 113, english: 'She gives me gray hair.', japanese: '彼女のせいで白髪が増えますよ。', category_id: 2 },
    { id: 114, english: 'He gives all his time to his work.', japanese: '彼は全ての時間を仕事に充てています。', category_id: 2 },
    { id: 115, english: 'Did the news give you a shock?', japanese: 'その知らせにショックを受けましたか？', category_id: 2 },
    { id: 116, english: 'My parents gave me a lot of love when I was a child.', japanese: '私が子供の頃に両親はたっぷり愛情を注いでくれた。', category_id: 2 },
    { id: 117, english: 'The principal always gives a long speech.', japanese: '校長先生はいつも長い演説をします。', category_id: 2 },
    { id: 118, english: 'Takumi offered to give us a ride home.', japanese: '彼は私たちを家まで送っていくと申し出ました。', category_id: 2 },
    { id: 119, english: 'It always gives us pleasure to walk in nature.', japanese: '自然の中を歩くのは私にとってはいつも楽しい。', category_id: 2 },
    { id: 120, english: 'I want yout to give your full attention to this job.', japanese: '私はあなたにこの仕事に最新の注意を払ってほしいです。', category_id: 2 },
    { id: 121, english: 'I am sorry that I gave you a lot of trouble.', japanese: '大変ご迷惑をおかけし申し訳ありません。', category_id: 2 },
    { id: 122, english: 'I heard someone give a shout.', japanese: '誰かが叫ぶのを聞きました。', category_id: 2 },
    { id: 123, english: 'Constant complaints from the customers gave him gray hair.', japanese: 'お客さんたちからの絶え間ない苦情のせいで彼は白髪になった。', category_id: 2 },
    { id: 124, english: 'She gives all her free time to reading books.', japanese: '彼女は暇な時間を全て本を読むことに充てています。', category_id: 2 },
    { id: 125, english: 'Would you give me a hand?', japanese: '手を貸してもらえますか？', category_id: 2 },
    { id: 126, english: 'My friend gave me his cold.', japanese: '友達に風邪をうつされました。', category_id: 2 },
    { id: 127, english: 'I gave some thought to the matter.', japanese: 'その問題についてちょっと考えてみました。', category_id: 2 },
    { id: 128, english: 'Did your teacher give you a date to turn in the report by?', japanese: '先生はあなたにレポートの提出期限を言いましたか？', category_id: 2 },
    { id: 129, english: '2 times 2 gives you four.', japanese: '２掛ける２は４。', category_id: 2 },
    { id: 130, english: 'She gave him three children.', japanese: '彼女は彼との間に三人の子供を産みました。', category_id: 2 },
    { id: 131, english: 'He gave no reason for his absence.', japanese: '彼は欠席の理由を言いませんでした。', category_id: 2 },
    { id: 132, english: 'I gave him a punch in the face.', japanese: '彼の顔にパンチをくらわしてやりました。', category_id: 2 },
    { id: 133, english: 'If you are interested in something, you shoule give it a try.', japanese: 'もしあなたが何かに興味があるならば、試してみるべきです。', category_id: 2 },
    { id: 134, english: 'Some people are giving out flyers in front of the station.', japanese: '駅前で何人かの人がチラシを配っています。', category_id: 2 },
    { id: 135, english: 'She asked me to give her a hand.', japanese: '彼女は私に手を貸すよう頼みました。', category_id: 2 },
    { id: 136, english: "I hope I didn't give you the flu.", japanese: 'あなたにインフルエンザをうつしたのではないといいんですけど。', category_id: 2 },
    { id: 137, english: 'I think we should give another thought to what to do.', japanese: '私たちはどうするのかを再考するべきだと私は思います。', category_id: 2 },
    { id: 138, english: "He hasn't given us a specific date for his visit yet.", japanese: '彼は訪問の具体的な日程をまだ私たちに言っていません。', category_id: 2 },
    { id: 139, english: 'Six devided by three gives you two.', japanese: '６割る３は２。', category_id: 2 },
    { id: 140, english: 'Kyoko became his wife and gave him three children.', japanese: 'きょうこは彼の妻になり彼との間に３人の子供を産みました。', category_id: 2 },
    { id: 141, english: 'Did she give a reason for not attending the meeting?', japanese: '彼女は会議に出席しなかった理由を言いましたか？', category_id: 2 },
    { id: 142, english: 'The old lady gave the robber a kick in the shin.', japanese: 'その老婦人は強盗のスネを蹴った。', category_id: 2 },
    { id: 143, english: 'I decided to give a try to taking a yoga class.', japanese: '私はヨガのクラスを受けてみることに決めました。', category_id: 2 },
    { id: 144, english: 'The teacher gave out handouts to the students.', japanese: 'その先生は生徒たちに配布物を配りました。', category_id: 2 },
    { id: 145, english: 'The government gave out the date of the national referendum.', japanese: '政府は国民投票の期日を発表しました。', category_id: 2 },
    { id: 146, english: 'If the food gives out, they will all die.', japanese: 'もし食料が尽きたら、彼らはみんな死ぬでしょう。', category_id: 2 },
    { id: 147, english: 'My legs gave out halfway there.', japanese: '脚が道半ばでへたばってしまった。', category_id: 2 },
    { id: 148, english: 'I gave away all my money to poor people.', japanese: '私は自分のお金を全て貧しい人に与えました。', category_id: 2 },
    { id: 149, english: 'She accidentally gave away the secret.', japanese: '彼女はうっかり秘密を漏らしてしまった。', category_id: 2 },
    { id: 150, english: 'The old bridge gave away.', japanese: 'その古い橋は崩落しました。', category_id: 2 },
    { id: 151, english: "They wouldn't give away to each other.", japanese: '彼らはお互いに譲ろうとしなかった。', category_id: 2 },
    { id: 152, english: 'The sun gives off light and heat.', japanese: '太陽は光と熱を放出します。', category_id: 2 },
    { id: 153, english: 'My boss gave it to me for coming late again.', japanese: '上司はまた遅刻したことで私を叱りました。', category_id: 2 },
    { id: 154, english: 'The enemy finally gave in.', japanese: '敵はついに降伏しました。', category_id: 2 },
    { id: 155, english: 'It was given out that the king passed away.', japanese: '王が逝去したことが発表されました。', category_id: 2 },
    { id: 156, english: 'When his patience gave out, she decided to get a divorce.', japanese: '忍耐が尽きた時、彼は離婚することを決めた。', category_id: 2 },
    { id: 157, english: 'She was afraid that the engine might give out.', japanese: '彼女はエンジンが止まってしまうかもしれないと恐れた。', category_id: 2 },
    { id: 158, english: 'My grandfather gave away all his books to a local library.', japanese: '祖父は自分の本を全て地元の図書館に寄付しました。', category_id: 2 },
    { id: 159, english: 'The smell of the perfume gave away that he had been with the woman.', japanese: '香水の匂いで彼がその女性と一緒にいたことがバレました。', category_id: 2 },
    { id: 160, english: 'The floor gave way under the weight of the furniture.', japanese: '家具の重さで床が抜けました。', category_id: 2 },
    { id: 161, english: 'The teacher gave way to anger and shouted at the student.', japanese: '先生は怒りを抑えきれずその生徒を怒鳴りました。', category_id: 2 },
    { id: 162, english: 'The actress was giving off a strong aura.', japanese: 'その女優は強烈なオーラを発していました。', category_id: 2 },
    { id: 163, english: 'His boss gave him a good talking-to when he repeated the same mistake.', japanese: '彼が同じ間違いを繰り返した時、彼の上司は彼をこってり叱りました。', category_id: 2 },
    { id: 164, english: 'He tried not to give in to temptation.', japanese: '彼は誘惑に負けないと頑張りました。', category_id: 2 },
    { id: 165, english: 'I put the coin into my pocket.', japanese: '私はポケットに硬貨を入れました。', category_id: 3 },
    { id: 166, english: 'He could not put what she felt into words.', japanese: '彼は自分の感じたことを言葉にできませんでした。', category_id: 3 },
    { id: 167, english: 'Is it possible to put this theory into practice?', japanese: 'この理論を実地に応用することはできますか？', category_id: 3 },
    { id: 168, english: 'Who put such an idea into her head?', japanese: '誰がそんな考えを彼女の頭に吹き込んだんですか？', category_id: 3 },
    { id: 169, english: 'I put everything I had into the job.', japanese: '私は持てる全てを仕事に注ぎ込みました。', category_id: 3 },
    { id: 170, english: 'He put the picture on the wall.', japanese: '彼はその絵を壁にかけました。', category_id: 3 },
    { id: 171, english: 'I put a stamp on the evnelope.', japanese: '私は封筒に切手を貼りました。', category_id: 3 },
    { id: 172, english: 'The doctor put her on a diet.', japanese: '医者は彼女に食事療法をさせました。', category_id: 3 },
    { id: 173, english: 'My brother put on his hat and left the room.', japanese: '兄は帽子をかぶって部屋を出ました。', category_id: 3 },
    { id: 174, english: 'When he said good-bye, she put on a sad face.', japanese: '彼がサヨナラを行った時、彼女は悲しい顔をしました。', category_id: 3 },
    { id: 175, english: 'The government put taxes on those goods.', japanese: '政府はそれらの商品に税金を課しました。', category_id: 3 },
    { id: 176, english: 'Please put your signature on this document.', japanese: 'この書類にご署名ください。', category_id: 3 },
    { id: 177, english: 'I saw him put the book into his bag.', japanese: '私は彼がその本を鞄に入れるのを見ました。', category_id: 3 },
    { id: 178, english: 'I found it hard to put what he felt into words.', japanese: '私は自分の感じたことを言葉にするのを難しく感じました。', category_id: 3 },
    { id: 179, english: 'I am going to put what I have learned here into practice.', japanese: '私はここで学んできたことを実践するつもりです。', category_id: 3 },
    { id: 180, english: 'Who do you think put such a stupid idea into her head?', japanese: 'あなたは誰がそんなに馬鹿げた考えを彼女の頭に吹き込んだのだと思いますか？', category_id: 3 },
    { id: 181, english: 'The artist put everything he had into creating the work.', japanese: 'その芸術家は持てる全てをその作品の創作に注ぎ込みました。', category_id: 3 },
    { id: 182, english: 'I put the kettle on the fire to make some coffee.', japanese: '私はコーヒーをいれるためにやかんを火にかけました。', category_id: 3 },
    { id: 183, english: 'Why did you put a sticky note on this page?', japanese: 'なぜこのページに付箋を貼ったんですか？', category_id: 3 },
    { id: 184, english: 'The doctor put the patient on medication.', japanese: '医者はその患者に薬物療法を施しました。', category_id: 3 },
    { id: 185, english: 'That man put on his glasses to read the newspaper.', japanese: 'あの男性は新聞を読むためにメガネをかけました。', category_id: 3 },
    { id: 186, english: 'Why are you putting on such a happy face?', japanese: 'なんでそんな嬉しそうな顔をしているんですか？', category_id: 3 },
    { id: 187, english: 'Heavy taxes will be put on these goods', japanese: 'これらの品物には重税が課されるでしょう。', category_id: 3 },
    { id: 188, english: 'She refused to put her signature on the contract.', japanese: '彼女は契約書に署名することを拒みました。', category_id: 3 },
    { id: 189, english: 'Put away your toys.', japanese: 'おもちゃを片付けなさい。', category_id: 3 },
    { id: 190, english: "I couldn't put away my doubts.", japanese: '私は疑念を捨て去ることができなかった。', category_id: 3 },
    { id: 191, english: 'She sang a lullaby to put her baby to sleep.', japanese: '彼女は赤ちゃんを寝かしつけるために子守唄を歌いました。', category_id: 3 },
    { id: 192, english: 'The vet put the sick dog to sleep.', japanese: '獣医はその病気の犬を安楽死させました。', category_id: 3 },
    { id: 193, english: 'The police officer told the man to put up his hands.', japanese: '警官はその男に手をあげるように言いました。', category_id: 3 },
    { id: 194, english: 'The enemy will put up a white flag soon.', japanese: '敵は間も無く白旗を挙げるでしょう。', category_id: 3 },
    { id: 195, english: 'They put up a fence around the land.', japanese: '彼らはその土地の周りに柵を立てました。', category_id: 3 },
    { id: 196, english: 'The party put him up for the presidency.', japanese: 'その党は彼女を大統領として候補に立てました。', category_id: 3 },
    { id: 197, english: 'That man put down his bag on the floor.', japanese: 'あの男は床にカバンを下ろしました。', category_id: 3 },
    { id: 198, english: 'I put down a $50,000 deposit on the house.', japanese: '私は家に5万ドルの手付金を払いました。', category_id: 3 },
    { id: 199, english: 'Mr.Sato quickly put down her phone number.', japanese: '佐藤さんは彼女の電話番号を素早く書き留めました。', category_id: 3 },
    { id: 200, english: 'He really likes putting down people.', japanese: '彼は人をこき下ろすのが本当に好きです。', category_id: 3 },
    { id: 201, english: 'I asked him to put away his books.', japanese: '私は彼に本を片付けるように頼みました。', category_id: 3 },
    { id: 202, english: 'This book will teach you how to put away your worries.', japanese: 'この本はあなたに不安の取り除き方を教えてくれるだろう。', category_id: 3 },
    { id: 203, english: 'He managed to put his children to bed.', japanese: '彼はなんとか子供達を寝かしつけました。', category_id: 3 },
    { id: 204, english: 'He was afraid that he might be put to death.', japanese: '彼は処刑されるかもしれないと恐れていました。', category_id: 3 },
    { id: 205, english: 'When I  greeted her, she put up her hand and smiled.', japanese: '私が彼女に挨拶した時、彼女は手を挙げて微笑みました。', category_id: 3 },
    { id: 206, english: "Why don't you put up a notice?", japanese: '告知を貼り出したらどうでしょうか？', category_id: 3 },
    { id: 207, english: 'People put up a monument to honor the soldiers.', japanese: '人々は兵士たちを称える記念碑を建てました。', category_id: 3 },
    { id: 208, english: 'We have to decide who to put up as a candidate.', japanese: '私たちは誰かを候補者に立てるかを決めなければなりません。', category_id: 3 },
    { id: 209, english: 'He tole everybody not to put down theirs bags there.', japanese: '彼はカバンをそこに下さないようにとみんなに言いました。', category_id: 3 },
    { id: 210, english: 'How much do I need to put down as a deposit?', japanese: '私は手付金としていくら支払う必要がありますか？', category_id: 3 },
    { id: 211, english: 'Please put down your name and address here.', japanese: 'ここにあなたのお名前と住所をご記入くださいませ。', category_id: 3 },
    { id: 212, english: "You shouldn't put down your husband like that.", japanese: 'あなたは奥さんをそんな風にこき下ろすべきではありません。', category_id: 3 },
    { id: 213, english: "Don't put off till tomorrow what you can do today.", japanese: '今日できることを明日まで延ばさないで。', category_id: 3 },
    { id: 214, english: "In the elevator, the woman's strong perfume put me off.", japanese: 'エレベーターの中で、その女性の強い香水に私は辟易しました。', category_id: 3 },
    { id: 215, english: 'My mother often asked me to put a thread through a needle.', japanese: '母はよく私に針に糸を通してくれと頼みます。', category_id: 3 },
    { id: 216, english: 'The doctor put me through a checkup.', japanese: '医者は私に健康診断を受けさせました。', category_id: 3 },
    { id: 217, english: "Don't forget to put out all the lights before you leave.", japanese: '出かける前に電気を全部消すのを忘れないでくださいね。', category_id: 3 },
    { id: 218, english: 'The depression put many people out of work.', japanese: '不況のせいで多くの人々が失業しました。', category_id: 3 },
    { id: 219, english: 'I want to put an end to this boring life.', japanese: '私はこの退屈な生活に終止符を打ちたい。', category_id: 3 },
    { id: 220, english: 'The atmosphere of the restaurant put me at ease.', japanese: 'そのレストランの雰囲気に私は寛ぎました。', category_id: 3 },
    { id: 221, english: 'He put his arm around my shoulders.', japanese: '彼は私の方に腕を回しました。', category_id: 3 },
    { id: 222, english: 'He puts his family before work.', japanese: '彼は仕事より家族を優先します。', category_id: 3 },
    { id: 223, english: 'We had to put off going on at trip to Europe.', japanese: '私たちはヨーロッパ旅行に行くのを延期しなければなりませんでした。', category_id: 3 },
    { id: 224, english: 'The heat put him off as he walked to the station.', japanese: '駅まで歩いた時、彼は暑さにげんなりしました。', category_id: 3 },
    { id: 225, english: 'They put the box through an X-ray.', japanese: '彼らはその箱をX線にかけました。', category_id: 3 },
    { id: 226, english: 'He is sorry that he put his wife through a lot of pain.', japanese: '彼は妻に大変苦労をさせたことを済まないと思っています。', category_id: 3 },
    { id: 227, english: 'When she put out the candle, it became completely dark.', japanese: '彼女がろうそくの火を消した時、真っ暗になりました。', category_id: 3 },
    { id: 228, english: "When I was put out of work, I didn't know what to do.", japanese: '失業した時、私はどうしていいか分かりませんでした。', category_id: 3 },
    { id: 229, english: 'Good luck put an end to my hardship.', japanese: '幸運のおかげで私の苦労は終わりました。', category_id: 3 },
    { id: 230, english: 'She is good at putting people at ease.', japanese: '彼女は人を寛がせるのが上手です。', category_id: 3 },
    { id: 231, english: 'When he put his arm around her shoulders, she said nothing.', japanese: '彼が彼女の肩に腕を回した時、彼女は何も言いませんでした。', category_id: 3 },
    { id: 232, english: 'He puts his children before anything else.', japanese: '彼は他の何よりも子供達を優先します。', category_id: 3 },
    { id: 233, english: 'He took a pen to write a letter.', japanese: '彼は手紙を書くためにペンを手に取りました。', category_id: 4 },
    { id: 234, english: 'She took my hand.', japanese: '彼女は私の手を取りました。', category_id: 4 },
    { id: 235, english: 'The doctor took my temperature.', japanese: '医者は私の熱を測りました。', category_id: 4 },
    { id: 236, english: 'I always takes a bath before I go to bed.', japanese: '私はいつも寝る前に風呂に入ります。', category_id: 4 },
    { id: 237, english: 'I took the first train this morning.', japanese: '私は今朝始発電車に乗りました。', category_id: 4 },
    { id: 238, english: 'I took a seat next to her.', japanese: '私は彼女の隣に腰をかけました。', category_id: 4 },
    { id: 239, english: "Why don't we take a short break?", japanese: '短い休憩を取りませんか？', category_id: 4 },
    { id: 240, english: 'We have to take measures to prevent accidents.', japanese: '私たちは事故防止のための措置を取らなければなりません。', category_id: 4 },
    { id: 241, english: 'Do you take lessons from a famous pianist?', japanese: 'あなたは有名なピアニストの方からレッスンを受けているんですか？', category_id: 4 },
    { id: 242, english: 'I think he should take your advice.', japanese: '彼はあなたの忠告を受け入れるべきだと私は思います。', category_id: 4 },
    { id: 243, english: 'She took a knife to cut the cake.', japanese: '彼女はケーキを切るためにナイフを手に取りました。', category_id: 4 },
    { id: 244, english: 'When I took her hand, she smiled shyly.', japanese: '僕が彼女の手を取った時、彼女は恥ずかしそうに微笑みました。', category_id: 4 },
    { id: 245, english: 'She took a late lunch today.', japanese: '私は今日遅い昼食を取りました。', category_id: 4 },
    { id: 246, english: 'After the yoga lesson, I took a shower quickly.', japanese: 'ヨガのレッスンの後、私は素早くシャワーを浴びました。', category_id: 4 },
    { id: 247, english: 'Last night I managed to take the last train.', japanese: '昨夜私はなんとか終電に乗りました。', category_id: 4 },
    { id: 248, english: 'The doctor told him to take a seat.', japanese: 'お医者さんは彼に腰掛けるように言いました。', category_id: 4 },
    { id: 249, english: 'I think she should take some rest.', japanese: '彼女は少し休憩を取るべきだと私は思います。', category_id: 4 },
    { id: 250, english: "She didn't even take the trouble to check her spelling.", japanese: '彼女は綴りを確認する手間さえ取りませんでした。', category_id: 4 },
    { id: 251, english: 'I am taking a course in psychology at college.', japanese: '私は大学で心理学の授業を履修しています。', category_id: 4 },
    { id: 252, english: "I can't believe she didn't take such a good offer.", japanese: '彼女がそんなに良い申し出を受け入れなかったなんて私は信じられません。', category_id: 4 },
    { id: 253, english: "I'll take this sweater.", japanese: 'このセータをいただきます。', category_id: 4 },
    { id: 254, english: 'It takes me about an hour to get to work.', japanese: '私は通勤に約１時間かかります。', category_id: 4 },
    { id: 255, english: 'He did not expect her to take his remark as an insult.', japanese: '彼は彼女が彼の発言を侮辱として受け取るとは予想しませんでした。', category_id: 4 },
    { id: 256, english: 'Before I went into the building, I took off my coat.', japanese: '建物に入る前に私はコートを脱ぎました。', category_id: 4 },
    { id: 257, english: 'He took a day off yesterday.', japanese: '彼は昨日１日休みを取りました。', category_id: 4 },
    { id: 258, english: "I'll take fifty percent off the price.", japanese: '50パーセント値引します。', category_id: 4 },
    { id: 259, english: 'I took off a lot of weight.', japanese: '私は大幅に減量しました。', category_id: 4 },
    { id: 260, english: 'Could you take down that box from the shelf?', japanese: '棚からあの箱を下ろしてくれませんか？', category_id: 4 },
    { id: 261, english: 'They took down the wall last week.', japanese: '彼らは先週壁を取り壊しました。', category_id: 4 },
    { id: 262, english: 'Please take down what I am going to say.', japanese: '私が言うことを書き留めてください。', category_id: 4 },
    { id: 263, english: 'The real estate agent was sure the rich man would take the house.', japanese: '不動産業者はその金持ちの人がその家を買うと確認していました。', category_id: 4 },
    { id: 264, english: 'Learning this language takes a lot of time and effort.', japanese: 'この言語を思えるには多くの時間と努力を要します。', category_id: 4 },
    { id: 265, english: "She shouldn't take what he says at face value.", japanese: '彼女は彼の言うことを額面通りに受け取るべきではありません。', category_id: 4 },
    { id: 266, english: 'When he saw her, he took off his hat and greeted her.', japanese: '彼女を見た時、彼は帽子を取り彼女に挨拶しました。', category_id: 4 },
    { id: 267, english: 'Can you take the afternoon off tomorrow.', japanese: 'あなたは明日の午後休むことができますか？', category_id: 4 },
    { id: 268, english: 'Could you take five percent off the price?', japanese: '5パーセントまけてくれませんか？', category_id: 4 },
    { id: 269, english: 'The doctor told him that he shoule take off at least five kilograms.', japanese: '医者は彼が少なくとも5キロ減量するべきだと言いました。', category_id: 4 },
    { id: 270, english: 'I took down the large bag from the rack for that lady.', japanese: '私はその女性のために大きなカバンを網棚から下ろしました。', category_id: 4 },
    { id: 271, english: 'The old building had to be taken down.', japanese: 'その古い建物は取り壊されなければなりませんでした。', category_id: 4 },
    { id: 272, english: "You don't have to take down everything the boss says.", japanese: 'あなたは上司の言うことを全て書き留める必要はありません。', category_id: 4 },
    { id: 273, english: 'I took my children to the amusemennt park.', japanese: '私は子供達を遊園地に連れて行きました。', category_id: 4 },
    { id: 274, english: 'This train will take you to Sakae.', japanese: 'この電車に乗れば栄に行けます。', category_id: 4 },
    { id: 275, english: 'You shoule take her age into consideration.', japanese: 'あなたは彼女の年齢を考慮に入れるべきです。', category_id: 4 },
    { id: 276, english: 'We had better take in the lanundry before it begins to rain.', japanese: '私たちは雨が降り始める前に洗濯物を取り込んだほうがいいです。', category_id: 4 },
    { id: 277, english: 'Will you take me in for the night tonight.', japanese: '今夜泊めてくれますか？', category_id: 4 },
    { id: 278, english: 'This will help  take in nutrition.', japanese: 'これは栄養を摂取する助けになるだろう。', category_id: 4 },
    { id: 279, english: "He didn't take in the lecture at all.", japanese: '彼はその講義が全然理解できなかった。', category_id: 4 },
    { id: 280, english: 'Since he had lost a lot of weight, he had to take the trousers in at the waist.', japanese: '彼はすごく体重が減ったので、ズボンのウエストを詰めなければなりませんでした。', category_id: 4 },
    { id: 281, english: 'The thief took away all my jewels.', japanese: 'その泥棒は私の宝石を全て持ち去りました。', category_id: 4 },
    { id: 282, english: 'The view from the mountain top took away his breath.', japanese: '山頂からの眺めに彼は息を呑みました。', category_id: 4 },
    { id: 283, english: 'Her work took her to Tokyo last month.', japanese: '彼女は仕事で先月東京に行きました。', category_id: 4 },
    { id: 284, english: 'His ability will take him to the top of this field.', japanese: '彼は有能なのでこの分野の第一人者になるでしょう。', category_id: 4 },
    { id: 285, english: 'I failed to take the time difference into consideration.', japanese: '私は時差を考慮に入れそこないました。', category_id: 4 },
    { id: 286, english: 'I asked her to take in the laundry.', japanese: '私は彼女に洗濯物を取り込むように頼みました。', category_id: 4 },
    { id: 287, english: 'She kindly took me in for a few days.', japanese: '彼女は親切にも数日私を泊めてくれました。', category_id: 4 },
    { id: 288, english: 'The doctor advised me to take in fewer calories.', japanese: '医者は私にカロリー摂取を抑えるように忠告しました。', category_id: 4 },
    { id: 289, english: "She didn't take in the explanation make in English.", japanese: '彼女は英語でされた説明を理解できませんでした。', category_id: 4 },
    { id: 290, english: 'He had his pants taken in at the waist.', japanese: '彼はズボンのウエストを詰めてもらいました。', category_id: 4 },
    { id: 291, english: 'She managed to take away the knife from the robber.', japanese: '彼女は強盗からなんとかナイフを奪いました。', category_id: 4 },
    { id: 292, english: 'When the prince saw Cinderella for the first time, her beauty took away his breath.', japanese: '初めてシンデレラを見た時、王子は彼女の美しさに息を呑みました。', category_id: 4 },
    { id: 293, english: 'Why do holidays go so fast?', japanese: 'なぜ休日はこんなに早くすぎるのでしょうか？', category_id: 5 },
    { id: 294, english: 'First prize went to him.', japanese: '彼が一等賞を取りました。', category_id: 5 },
    { id: 295, english: 'This article will have to go.', japanese: 'この記事は削除しなければならないでしょう。', category_id: 5 },
    { id: 296, english: 'How did the exam go?', japanese: '試験はどうでしたか？', category_id: 5 },
    { id: 297, english: 'Everything went well.', japanese: '全てがうまく行きました。', category_id: 5 },
    { id: 298, english: 'Her car went for three million yen.', japanese: '彼女の車は300万円で売れました。', category_id: 5 },
    { id: 299, english: 'Many dictionaries go on that shelf.', japanese: '多くの辞書はあの棚に入ります。', category_id: 5 },
    { id: 300, english: 'All my money goes to gambling.', japanese: '私のお金は全てギャンブルに費やされます。', category_id: 5 },
    { id: 301, english: 'His fever will go in a few days.', japanese: '彼の熱は数日で下がるでしょう。', category_id: 5 },
    { id: 302, english: 'They go swimming every Saturday.', japanese: '彼らは毎週土曜日に泳ぎに行きます。', category_id: 5 },
    { id: 303, english: 'The summer went so fast.', japanese: 'その夏は非常に早く過ぎました。', category_id: 5 },
    { id: 304, english: 'Who did the prize go to.', japanese: '誰がその賞を取ったのですか？', category_id: 5 },
    { id: 305, english: 'The company made more than one hundred people go.', japanese: 'その会社は100人以上の人を解雇しました。', category_id: 5 },
    { id: 306, english: 'How are things going?', japanese: '調子はどうですか？', category_id: 5 },
    { id: 307, english: "I don't know what went wrong.", japanese: '私には何がまずかったのか分かりません。', category_id: 5 },
    { id: 308, english: 'Her house will go for more than one hundred million yen.', japanese: '彼女の家は一億円を超える値で売れるでしょう。', category_id: 5 },
    { id: 309, english: 'Where does that table go?', japanese: 'あのテーブルはどこに置きますか？', category_id: 5 },
    { id: 310, english: 'Millions of dollars went to the development of the product.', japanese: '何百万ドルもその商品の開発に使われました。', category_id: 5 },
    { id: 311, english: 'Has the pain gone?', japanese: '痛みは無くなりましたか？', category_id: 5 },
    { id: 312, english: "Why don't we go to karaoke tomorrow?", japanese: '明日はカラオケに行きませんか？', category_id: 5 },
    { id: 313, english: 'If she hears that, she will go mad.', japanese: '彼女がそれを聞いたら怒るだろう。', category_id: 5 },
    { id: 314, english: 'Why did she go wild?', japanese: '彼女はなぜ逆上したのですか？', category_id: 5 },
    { id: 315, english: 'The milk went bad.', japanese: '牛乳は腐りました。', category_id: 5 },
    { id: 316, english: 'Let that child go free.', japanese: 'あの子供を開放して。', category_id: 5 },
    { id: 317, english: 'As soon as my innocence was proven, I went free.', japanese: '無実が証明されるとすぐに私は釈放されました。', category_id: 5 },
    { id: 318, english: 'The bad guys went unpunished.', japanese: '悪党たちは罰されずに済みました。', category_id: 5 },
    { id: 319, english: 'The mistake went unnoticed.', japanese: 'そのミスは気づかれぬままになりました。', category_id: 5 },
    { id: 320, english: 'He is going out with a pretty girl.', japanese: '彼は綺麗な女の子と付き合っています。', category_id: 5 },
    { id: 321, english: 'The plane went out of sight.', japanese: '飛行機は見えなくなりました。', category_id: 5 },
    { id: 322, english: 'These types of clothes went out of fashion long ago.', japanese: 'これらのタイプの服はとっくの昔に廃れました。', category_id: 5 },
    { id: 323, english: 'Did his boss go mad when he made the mistake?', japanese: '彼がその間違いを犯した時、上司は怒りましたか？', category_id: 5 },
    { id: 324, english: 'The man went wild suddenly.', japanese: 'その男は突然逆上しました。', category_id: 5 },
    { id: 325, english: "Don't make the eggs go bad.", japanese: '卵を腐らせないでくださいね。', category_id: 5 },
    { id: 326, english: 'She let the bird go free.', japanese: '彼女はその鳥を放してやりました。', category_id: 5 },
    { id: 327, english: 'He will go free soon.', japanese: '彼は間もなく釈放されるでしょう。', category_id: 5 },
    { id: 328, english: "Don't think that such a deed will go unpunished.", japanese: 'そんな行為をしてただけですむと思うなよ。', category_id: 5 },
    { id: 329, english: 'Why did this defect go unnoticed?', japanese: 'なぜこの欠陥は気付かれないままになったのですか？', category_id: 5 },
    { id: 330, english: 'How long has she been going out with him?', japanese: '彼女は彼とどれぐらいの間付き合っているんですか？', category_id: 5 },
    { id: 331, english: 'I kept waving her hand until the train went out of sight.', japanese: '私は電車が見えなくなるまで手を振り続けました。', category_id: 5 },
    { id: 332, english: 'Her favorite restaurant went out of business last month.', japanese: '彼女のお気に入りのレストランが先月廃業してしまいました。', category_id: 5 },
    { id: 333, english: "It's a shame that such a good book has gone out of print.", japanese: 'こんなにいい本が絶版になってしまったのは残念です。', category_id: 5 },
    { id: 334, english: 'Which candidate will you go for?', japanese: 'あなたはどちらの候補者に投票しますか？', category_id: 5 },
    { id: 335, english: "I don't think he would go for this type of place.", japanese: 'こういう場所を彼が気にいるとは僕は思わないです。', category_id: 5 },
    { id: 336, english: 'When the night fell, the temperature went down sharply.', japanese: '夜になると気温が急に下がりました。', category_id: 5 },
    { id: 337, english: 'When the earthquake occurred, the wall went down.', japanese: '地震が起こった時、壁が崩れました。', category_id: 5 },
    { id: 338, english: 'They should buy a house before land prices go up.', japanese: '地価が上がる前に彼らは家を買うべきです。', category_id: 5 },
    { id: 339, english: 'A scream of protest went up from the customers.', japanese: 'お客様たちから抗議の叫びが上がりました。', category_id: 5 },
    { id: 340, english: 'All the documents went up in flames.', japanese: '全ての文書が燃え尽きてしまいました。', category_id: 5 },
    { id: 341, english: 'All my efforts and preparations might go up in flames unless we are careful.', japanese: '注意しないと私の努力と準備がすべて水の泡となってしまうかもしれません。', category_id: 5 },
    { id: 342, english: 'The patient went into a coma.', japanese: '患者さんは昏睡状態に陥りました。', category_id: 5 },
    { id: 343, english: 'Does this dish go well with red wine or white wine?', japanese: 'この料理は赤ワインと合いますか、白ワインと合いますか？', category_id: 5 },
    { id: 344, english: 'His turn came last.', japanese: '彼の順番は最後でした。', category_id: 6 },
    { id: 345, english: 'The news came as a surprise to me.', japanese: 'その知らせは私にとって驚きでした。', category_id: 6 },
    { id: 346, english: "I won't change my mind whatever comes.", japanese: '何が起ころうと私の気持ちは変わりません。', category_id: 6 },
    { id: 347, english: 'Big money will come from this business.', japanese: 'このビジネスすごく儲かるでしょう。', category_id: 6 },
    { id: 348, english: "My child's life comes before anything else.", japanese: '私の子供の命が他の何よりも大事です。', category_id: 6 },
    { id: 349, english: 'Her confidence will come back soon.', japanese: '彼女は間も無く自信を取り戻すでしょう。', category_id: 6 },
    { id: 350, english: 'This sweater comes in all sizes.', japanese: 'このセーターは全サイズあります。', category_id: 6 },
    { id: 351, english: 'When did the meeting come to an end?', japanese: 'その会議はいつ終わったのですか？', category_id: 6 },
    { id: 352, english: 'All my effort came to nothing.', japanese: '私の努力は全て無駄になりました。', category_id: 6 },
    { id: 353, english: 'He finally came to an agreement.', japanese: '彼はついに手を打ちました。', category_id: 6 },
    { id: 354, english: 'When will my turn come?', japanese: '私の番はいつですか？', category_id: 6 },
    { id: 355, english: 'Her sudden death came as a shock to his fans.', japanese: '彼女の急死はファンにとって衝撃でした。', category_id: 6 },
    { id: 356, english: 'Accidents came one after another.', japanese: '次から次へと事故が起こりました。', category_id: 6 },
    { id: 357, english: 'I belived that big money would come from the invention.', japanese: '私はその発明で大儲けできると信じていました。', category_id: 6 },
    { id: 358, english: 'Does money come before anything else for him?', japanese: '彼にとってはお金が何よりも大切ですか？', category_id: 6 },
    { id: 359, english: 'How did his confidence come back?', japanese: 'どうやって彼は自信を回復したのですか？', category_id: 6 },
    { id: 360, english: 'This car comes in three colors.', japanese: 'この車は３色あります。', category_id: 6 },
    { id: 361, english: 'All good things must come to an end.', japanese: '良いことは皆、必ず終わるものです。', category_id: 6 },
    { id: 362, english: 'All the trouble and money may come to nothing.', japanese: '手間とお金が全て無駄になってしまうかもしれません。', category_id: 6 },
    { id: 363, english: 'How did you come to that conclusion?', japanese: 'あなたはどうやってその結論に至ったのですか？', category_id: 6 },
    { id: 364, english: 'The bill only came to five thousand yen.', japanese: 'お勘定はたったの五千円でした。', category_id: 6 },
    { id: 365, english: 'The ship came into sight.', japanese: 'その船が見えました。', category_id: 6 },
    { id: 366, english: 'A good idea came into my mind.', japanese: 'いい考えが私の頭に浮かびました。', category_id: 6 },
    { id: 367, english: 'The truth will come out someday.', japanese: '真実がいつか明るみに出るでしょう。', category_id: 6 },
    { id: 368, english: 'Cherry blossoms will come out soon.', japanese: '間も無く桜の花が咲くでしょう。', category_id: 6 },
    { id: 369, english: 'The pictures she took in Paris came out well.', japanese: '彼女はパリで撮った写真はよく写っていました。', category_id: 6 },
    { id: 370, english: 'He heard someone come down from upstairs.', japanese: '彼は誰かが階下から降りてくるのが聞こえました。', category_id: 6 },
    { id: 371, english: 'Fortunately nobody was in the room when the roof came down.', japanese: '屋根が落ちた時、幸い誰も部屋にいませんでした。', category_id: 6 },
    { id: 372, english: 'I came down with a cold last week.', japanese: '私は先週風邪にかかりました。', category_id: 6 },
    { id: 373, english: 'The rich family came down in the world after the war.', japanese: 'その金持ちの一家は戦後落ちぶれてしまいました。', category_id: 6 },
    { id: 374, english: 'What does the bill come to?', japanese: 'お勘定はいくらになりますか？', category_id: 6 },
    { id: 375, english: 'A black car came into sight.', japanese: '黒い車が見えました。', category_id: 6 },
    { id: 376, english: 'Good ideas often come into his mind while walking.', japanese: '彼は歩いている間によくいい考えが頭に浮かびます。', category_id: 6 },
    { id: 377, english: 'I was afraid that my secret might come out.', japanese: '私は自分の秘密が明るみに出るのではないかと恐れていました。', category_id: 6 },
    { id: 378, english: 'Many flowers have come out in her garden.', japanese: 'たくさんの花が彼女の庭で咲きました。', category_id: 6 },
    { id: 379, english: "I don't come out well in pictures.", japanese: '私は写真写りが良くないです。', category_id: 6 },
    { id: 380, english: 'They began to come down the mountain.', japanese: '彼らは下山し始めました。', category_id: 6 },
    { id: 381, english: 'The strong wind made the pine tree come down.', japanese: '強風で松の木が倒れました。', category_id: 6 },
    { id: 382, english: 'He came down with the flu last month.', japanese: '彼は先月インフルエンザにかかりました。', category_id: 6 },
    { id: 383, english: 'The once famous actress came down in the world.', japanese: 'そのかつての有名女優は落ちぶれてしまいました。', category_id: 6 },
    { id: 384, english: 'Her hair comes to her waist.', japanese: '彼女の髪は腰まで届きます。', category_id: 6 },
    { id: 385, english: 'It all comes down to money in the end.', japanese: '全てはつまるところお金です。', category_id: 6 },
    { id: 386, english: 'The water came up to my chin.', japanese: '水は私の顎に達しました。', category_id: 6 },
    { id: 387, english: 'My level did not come up to the standards.', japanese: '私のレベルは基準に達しませんでした。', category_id: 6 },
    { id: 388, english: 'They came through the gate.', japanese: '彼らは門を通り過ぎて来ました。', category_id: 6 },
    { id: 389, english: 'He came through a serious illness.', japanese: '彼は大病を乗り越えました。', category_id: 6 },
    { id: 390, english: 'A button came off my shirt.', japanese: '私のシャツのボタンが一つ取れました。', category_id: 6 },
    { id: 391, english: 'A cloud came over the mountain.', japanese: '雲が山にかかりました。', category_id: 6 },
    { id: 392, english: "My son's twentieth birthday will come around next month.", japanese: '来月息子の２０歳の誕生日です。', category_id: 6 },
    { id: 393, english: 'Money will come and go.', japanese: '金は天下の回りもの。', category_id: 6 },
    { id: 394, english: 'My hair comes down to my shoulders.', japanese: '私の髪は肩まで届きます。', category_id: 6 },
    { id: 395, english: 'It comes down to personal preference.', japanese: '結局は個々人の好みの問題です。', category_id: 6 },
    { id: 396, english: 'The water will come up to his chest.', japanese: '水は彼の胸に達するでしょう。', category_id: 6 },
    { id: 397, english: 'The quality of the product did not come up to the criterion.', japanese: 'その製品の品質は基準を満たしませんでした。', category_id: 6 },
    { id: 398, english: 'The magician came through the wall.', japanese: '魔術師は壁を通り抜けて来ました。', category_id: 6 },
    { id: 399, english: 'I came through a major operation.', japanese: '私は大手術を乗り越えました。', category_id: 6 },
    { id: 400, english: "This ketchup stain won't come off.", japanese: 'このケチャップのシミはどうしても落ちません。', category_id: 6 },
    { id: 401, english: 'A black cloud came over the moon.', japanese: '悪運が月にかかりました。', category_id: 6 },
    { id: 402, english: 'I feel that my birthday comes around quicker each year.', japanese: '毎年誕生日がより早く巡ってくると私は感じます。', category_id: 6 },
    { id: 403, english: 'Success will come and go.', japanese: '成功などはかないものです。', category_id: 6 },
    { id: 404, english: 'She made a sand castle on the beach.', japanese: '彼女は海岸で砂の城を作りました。', category_id: 7 },
    { id: 405, english: 'My grandfather made a fortune in the oil business.', japanese: '私の祖父は石油ビジネスで財を成しました。', category_id: 7 },
    { id: 406, english: 'That model makes two hundred thousand yen an hour.', japanese: 'あのモデルは１時間に20万円稼ぎます。', category_id: 7 },
    { id: 407, english: 'I would like to make a reservation for a single room.', japanese: 'シングルの予約をしたいのですが。', category_id: 7 },
    { id: 408, english: 'He always makes a fuss about trifles.', japanese: '彼はいつも些細なことで騒ぎ立てます。', category_id: 7 },
    { id: 409, english: 'He made a vow to stop smoking.', japanese: '彼は近縁の誓いを立てました。', category_id: 7 },
    { id: 410, english: "I will make him an offer that he can't refuse.", japanese: '私は彼が断れない申し出をしよう。', category_id: 7 },
    { id: 411, english: 'Everybody made a rush for the exit.', japanese: 'みんなが出口に突進しました。', category_id: 7 },
    { id: 412, english: 'She makes his living by teaching English.', japanese: '彼女は英語を教えて生計を立てています。', category_id: 7 },
    { id: 413, english: 'Shall I make some sandwiches for you?', japanese: 'あなたのためにサンドイッチを作りましょうか？', category_id: 7 },
    { id: 414, english: 'He made a lot of money on the stock market.', japanese: '彼は株で大儲けしました。', category_id: 7 },
    { id: 415, english: 'She make about one thousand dollars a week.', japanese: '彼女の稼ぎは週に焼く1000ドルです。', category_id: 7 },
    { id: 416, english: 'I saw the car make a sharp turn.', japanese: '私はその車が急に曲がるのを見ました。', category_id: 7 },
    { id: 417, english: 'She will make arrangements for everything.', japanese: '彼女が万事手配いたします。', category_id: 7 },
    { id: 418, english: 'What are they making a fuss about?', japanese: '彼らは何について騒いでいるんですか？', category_id: 7 },
    { id: 419, english: 'He made a vow never to do such a thing again.', japanese: '彼は二度とそんなことをしないと誓いました。', category_id: 7 },
    { id: 420, english: 'Let me make a suggestion.', japanese: '私に提案させてください。', category_id: 7 },
    { id: 421, english: 'She made a beautiful dive into the pool.', japanese: '彼女はプールに見事に飛び込みました。', category_id: 7 },
    { id: 422, english: "I did not know how to make a living.", japanese: '私はどうやって生計を立てていいか分かりませんでした。', category_id: 7 },
    { id: 423, english: 'She will make a good journalist.', japanese: '彼女はいいジャーナリストになるでしょう。', category_id: 7 },
    { id: 424, english: "This makes the third time you've said the same thing today.", japanese: 'これであなたが同じことを言うのは今日三度目です。', category_id: 7 },
    { id: 425, english: 'The novel made me.', japanese: 'その小説で私は成功しました。', category_id: 7 },
    { id: 426, english: 'The accident made the front page of the newspaper.', japanese: 'その事故は新聞の一面記事になりました。', category_id: 7 },
    { id: 427, english: 'This makes her third book.', japanese: 'これが彼女の三冊目の本です。', category_id: 7 },
    { id: 428, english: 'Such words will make you enemies.', japanese: 'そんなことを言うと敵ができますよ。', category_id: 7 },
    { id: 429, english: 'He usually make it to over one hundred kilometers an hour on expressways.', japanese: '彼は高速道路では通常時速100キロ以上出します。', category_id: 7 },
    { id: 430, english: 'She will make it as a writer.', japanese: '彼女は作家として成功するでしょう。', category_id: 7 },
    { id: 431, english: 'Hurry up, and you will make the bus.', japanese: '急ぎなさい、そうすればバスに乗れますよ。', category_id: 7 },
    { id: 432, english: 'She was made to be a singer.', japanese: '彼女は歌手になるために生まれました。', category_id: 7 },
    { id: 433, english: 'Do you think he will make her a good husband?', japanese: '彼は彼女にとって良い夫になると思いますか？', category_id: 7 },
    { id: 434, english: "This makes the second time I've been here.", japanese: '私がここにくるのはこれで二度目です。', category_id: 7 },
    { id: 435, english: 'Her performance made the movie.', japanese: '彼女の演技でその映画は成功しました。', category_id: 7 },
    { id: 436, english: "The disaster make the seven o'clock news.", japanese: 'その災害は7時のニュースで報じられました。', category_id: 7 },
    { id: 437, english: "That made the director's fifth film.", japanese: 'それがその監督の５作目の映画でした。', category_id: 7 },
    { id: 438, english: 'His arrogant attitude made him enemies.', japanese: '傲慢な態度のせいで彼には敵ができました。', category_id: 7 },
    { id: 439, english: 'Have you ever made it to over 200 kilometers per hour?', japanese: '200キロ以上出したことがありますか？', category_id: 7 },
    { id: 440, english: 'I never made it as a boxer.', japanese: '私はボクサーとして成功することは決してありませんでした。', category_id: 7 },
    { id: 441, english: 'I am going to have a party this weekend. Can you make it?', japanese: '私はこの週末にパーティーを開きます。来られますか？', category_id: 7 },
    { id: 442, english: 'He and she are made for each other.', japanese: '彼と彼女はお似合いのカップルです。', category_id: 7 },
    { id: 443, english: 'He always make much of my opinions.', japanese: '彼あhいつも私の意見を重視します。', category_id: 7 },
    { id: 444, english: "He couldn't make much of the professor's lecture.", japanese: '彼はその教授の講義をあまり理解できませんでした。', category_id: 7 },
    { id: 445, english: 'I will make the most of this opportunity.', japanese: '私はこの機会を最大限に活用します。', category_id: 7 },
    { id: 446, english: 'Stop making fun of her.', japanese: '彼女をからかうのはやめてください。', category_id: 7 },
    { id: 447, english: 'This sentence does not make sense.', japanese: 'この文は意味を成しません。', category_id: 7 },
    { id: 448, english: 'The good news made us happy.', japanese: 'その良い知らせに私たちは喜びました。', category_id: 7 },
    { id: 449, english: 'My father made me go there.', japanese: '父は私をそこへ行かせました。', category_id: 7 },
    { id: 450, english: 'She made for the door.', japanese: '彼女はドアに向かいました。', category_id: 7 },
    { id: 451, english: 'This will make for mutual understanding.', japanese: 'これは相互理解に役立つだろう。', category_id: 7 },
    { id: 452, english: 'Has he made up a list yet?', japanese: '彼はもうリストを作成しましたか？', category_id: 7 },
    { id: 453, english: 'The police made up the evidence.', japanese: '警察は証拠をでっちあげました。', category_id: 7 },
    { id: 454, english: 'He will make up with his girlfriend soon.', japanese: '彼は間もなく恋人と仲直りするだろう。', category_id: 7 },
    { id: 455, english: 'People over sixty make up twenty percent of the population.', japanese: '６０歳を過ぎている人々が、人口の２０%を占めています。', category_id: 7 },
    { id: 456, english: "You shouldn't make light of your injury.", japanese: 'あなたは自分の怪我を軽く見るべきではありません。', category_id: 7 },
    { id: 457, english: 'What did you make of this movie?/I make nothing of it.', japanese: 'あなたはこの映画をどう解釈しました？/全然分かりませんでした。', category_id: 7 },
    { id: 458, english: 'He made the most of his stay in Tokyo to improve his Japanese.', japanese: '彼は東京滞在を日本語上達のために最大限に活用しました。', category_id: 7 },
    { id: 459, english: 'Why do you always make fun of her?', japanese: 'なぜあなたはいつも彼女をからかうんですか？', category_id: 7 },
    { id: 460, english: "What that man said didn't make sense to me.", japanese: 'あの男性が言ったことは私には訳がわからなかった。', category_id: 7 },
    { id: 461, english: "He couldn't make himself understood in Spanish.", japanese: '彼のスペイン語は通じませんでした。', category_id: 7 },
    { id: 462, english: 'She is the kind of person who can make things happen.', japanese: '彼女は実行力のある人です。', category_id: 7 },
    { id: 463, english: 'The ship was making for the island.', japanese: '船はその島に向かっていました。', category_id: 7 },
    { id: 464, english: 'A glass of wine sometimes makes for a good sleep.', japanese: 'ワインをグラス一杯飲むとよく眠れることが時々あります。', category_id: 7 },
    { id: 465, english: 'He made up a team to tackle the problem.', japanese: '彼はその問題に取り組むためのチームを作りました。', category_id: 7 },
    { id: 466, english: 'That man always makes up stories.', japanese: 'あの男性はいつも話をでっちあげます。', category_id: 7 },
    { id: 467, english: 'Have you made up with him yet?', japanese: 'あなたなもう彼と仲直りしたのですか？', category_id: 7 },
    { id: 468, english: 'What percent of you sales does this product make up?', japanese: 'この製品は御社の売り上げの何%を占めているのですか？', category_id: 7 },
    { id: 469, english: 'That woman have beautiful eyes.', japanese: 'あの女性の目は美しいです。', category_id: 8 },
    { id: 470, english: 'She had a baby last week.', japanese: '彼女は先週赤ちゃんを産みました。', category_id: 8 },
    { id: 471, english: 'He has a bad cold.', japanese: '彼はひどい風邪をひいています。', category_id: 8 },
    { id: 472, english: 'She wants to have a pet cat.', japanese: '彼女は猫を飼いたがっています。', category_id: 8 },
    { id: 473, english: 'Di you have a good time in Okinawa.', japanese: '沖縄では楽しく過ごしましたか？', category_id: 8 },
    { id: 474, english: 'A year has twelve months.', japanese: '一年は１２カ月です。', category_id: 8 },
    { id: 475, english: 'This room has three windows.', japanese: 'この部屋には窓が三つあります。', category_id: 8 },
    { id: 476, english: 'We had a lot of rain yesterday.', japanese: '昨日は大雨でした。', category_id: 8 },
    { id: 477, english: 'Have a seat, please.', japanese: 'どうぞお座りください。', category_id: 8 },
    { id: 478, english: 'He has a good memory.', japanese: '彼は記憶力がいいです。', category_id: 8 },
    { id: 479, english: 'What a sweet voice she has!', japanese: '彼女はなんと甘美な声をしているのでしょう！', category_id: 8 },
    { id: 480, english: 'She had a son by her first husband.', japanese: '彼女は最初の夫との間に息子を産みました。', category_id: 8 },
    { id: 481, english: 'He had the flu last month.', japanese: '彼は先月インフルエンザにかかりました。', category_id: 8 },
    { id: 482, english: 'She will have a pet dog if I buy a house.', japanese: 'もし家を買ったら彼女は犬を飼うだろう。', category_id: 8 },
    { id: 483, english: 'He must be having a good time in Tokyo.', japanese: '彼は東京で楽しんでいるに違いないです。', category_id: 8 },
    { id: 484, english: 'August has thirty-one days.', japanese: '８月は３１日あります。', category_id: 8 },
    { id: 485, english: 'Does his house have a garden?', japanese: '彼の家には庭がありますか？', category_id: 8 },
    { id: 486, english: 'Did you have any snow over there?', japanese: 'そちらでは雪が降りましたか？', category_id: 8 },
    { id: 487, english: "Why don't you have a seat?", japanese: 'お座りになったらどうですか？', category_id: 8 },
    { id: 488, english: 'I have a bad memory.', japanese: '私は記憶力が悪いです。', category_id: 8 },
    { id: 489, english: 'She has a good memory for faces.', japanese: '彼女は人に顔を覚えるのが得意です。', category_id: 8 },
    { id: 490, english: 'He has a grudge against his ex-boss.', japanese: '彼は元上司を恨んでいます。', category_id: 8 },
    { id: 491, english: 'He has a liking for jazz.', japanese: '彼はジャズが好きです。', category_id: 8 },
    { id: 492, english: 'He had the kindness to drive me home.', japanese: '彼は親切にも私を家まで車で送ってくれました。', category_id: 8 },
    { id: 493, english: 'I had trouble understanding what the foreigner was saying.', japanese: '私はその外国人が言っていることを理解するのに苦労しました。', category_id: 8 },
    { id: 494, english: 'She had a hat on.', japanese: '彼女は帽子をかぶっていました。', category_id: 8 },
    { id: 495, english: 'I had her cook dinner.', japanese: '私は彼女に夕食を作ってもらいました。', category_id: 8 },
    { id: 496, english: 'Who did you have check your PC?', japanese: 'あなたは誰にパソコンを点検してもらったんですか？', category_id: 8 },
    { id: 497, english: 'I would like to have my watch repaired.', japanese: '私は時計を修理してもらいたい。', category_id: 8 },
    { id: 498, english: 'He have no idea where he had his wallet stolen.', japanese: '彼はどこで財布を盗まれたのか全く分かりません。', category_id: 8 },
    { id: 499, english: 'He has a bad memory for names.', japanese: '彼は名前を覚えるのが苦手です。', category_id: 8 },
    { id: 500, english: 'She has never had a grudge against anybody.', japanese: '彼女は誰も恨んだことなどありません。', category_id: 8 },
    { id: 501, english: 'I have a preference for being alone.', japanese: '私は一人でいるのが好きです。', category_id: 8 },
    { id: 502, english: 'The man had the kindness to teach me how to use the machine.', japanese: 'その男性は親切にもその機械の使い方を教えてくれました。', category_id: 8 },
    { id: 503, english: "You won't have any trouble finding her house.", japanese: 'あなたは彼女の家を簡単に見つけられるでしょう。', category_id: 8 },
    { id: 504, english: 'Did the woman have glasses on?', japanese: 'その女性は眼鏡をかけていましたか？', category_id: 8 },
    { id: 505, english: "Why don't you have her do this job?", japanese: '彼にこの仕事をしてもらってはどうですか？', category_id: 8 },
    { id: 506, english: 'Did you have someone proofread your draft?', japanese: '誰かに原稿を校正してもらいましたか？', category_id: 8 },
    { id: 507, english: "Let's have our picture taken here.", japanese: 'ここで私たちの写真を撮ってもらいましょう。', category_id: 8 },
    { id: 508, english: 'He should have that cut looked at.', japanese: '彼はその傷を診てもらうべきです。', category_id: 8 },
    { id: 509, english: 'She did her duty.', japanese: '彼女は自分の義務を果たしました。', category_id: 9 },
    { id: 510, english: 'I do the laundry every day.', japanese: '私は毎日洗濯をします。', category_id: 9 },
    { id: 511, english: 'Would you do me a favor?', japanese: 'お願いを聞いていただけませんか？', category_id: 9 },
    { id: 512, english: 'I will do my best.', japanese: '私は全力を尽くします。', category_id: 9 },
    { id: 513, english: 'I want someone to do the room at once.', japanese: '私は誰かにすぐに部屋を掃除してほしいです。', category_id: 9 },
    { id: 514, english: 'Who did these flowers?', japanese: '誰がこれらの花をいけたんですか？', category_id: 9 },
    { id: 515, english: 'How long has she been doing yoga?', japanese: '彼女はどのくらいの間ヨガをやっていますか？', category_id: 9 },
    { id: 516, english: 'He usually does the dishes after dinner.', japanese: '夕食後はたいてい彼が皿を洗います。', category_id: 9 },
    { id: 517, english: 'They did the sights of Nagoya.', japanese: '彼らは名古屋の名所を見物した。', category_id: 9 },
    { id: 518, english: 'Is she good at doing figures?', japanese: '彼女は計算をするのが得意ですか？', category_id: 9 },
    { id: 519, english: 'He have to do his duty.', japanese: '彼は自分の義務を果たさなければなりません。', category_id: 9 },
    { id: 520, english: 'She asked me to do the shopping.', japanese: '彼女は私に買い物をするように頼みました。', category_id: 9 },
    { id: 521, english: 'He asked me if I could do him a favor.', japanese: '彼は私に願いを聞いてもらえるかと頼みました。', category_id: 9 },
    { id: 522, english: 'All you have to do is do your best.', japanese: 'あなたは全力を尽くしさえすればいいですよ。', category_id: 9 },
    { id: 523, english: 'They have him do the house once a week.', japanese: '彼らは彼に週に一回家を掃除してもらっています。', category_id: 9 },
    { id: 524, english: 'My grandfather is doing the garden.', japanese: '祖父は庭いじりをしています。', category_id: 9 },
    { id: 525, english: 'He was doing wrestling at college.', japanese: '彼は大学でレスリングをやっていました。', category_id: 9 },
    { id: 526, english: 'She made me do the dishes.', japanese: '彼女は私に皿を洗わせました。', category_id: 9 },
    { id: 527, english: 'After doing the sights of the city, we had dinner at a nice restaurant.', japanese: 'その年の名所見物をした後に、私たちは素敵なレストランで夕食を食べました。', category_id: 9 },
    { id: 528, english: 'I have never been good at doing figures.', japanese: '私は計算するのが得意だったことがありません。', category_id: 9 },
    { id: 529, english: 'I want to do a book someday.', japanese: '私はいつか本を書きたいです。', category_id: 9 },
    { id: 530, english: 'What does she do?', japanese: '彼女の仕事は何ですか？', category_id: 9 },
    { id: 531, english: 'That man did time for robbery.', japanese: 'あの男性は強盗で服役しました。', category_id: 9 },
    { id: 532, english: 'This medicine will do her good.', japanese: 'この薬は彼女に効くでしょう。', category_id: 9 },
    { id: 533, english: 'Too much exercise will do you harm.', japanese: '過度な運動はあなたにとって害になります。', category_id: 9 },
    { id: 534, english: "He can't do without you.", japanese: '彼は君なしではやっていけないです。', category_id: 9 },
    { id: 535, english: 'He is doing pretty well at school.', japanese: '彼は割と成績が良いです。', category_id: 9 },
    { id: 536, english: 'I am doing law at college.', japanese: '私は大学で法律を専攻しています。', category_id: 9 },
    { id: 537, english: 'A compact car will do.', japanese: '小型車で結構です。', category_id: 9 },
    { id: 538, english: 'What is done is done.', japanese: '終わったことは終わったことです。', category_id: 9 },
    { id: 539, english: 'I heard that the writter would do a film.', japanese: '私はその作家が映画を撮ると聞きました。', category_id: 9 },
    { id: 540, english: 'I asked him what he did.', japanese: '私は彼に何の仕事をしているのか尋ねました。', category_id: 9 },
    { id: 541, english: 'What did he do time for?', japanese: '彼は何の罪で服役したのですか？', category_id: 9 },
    { id: 542, english: "I don't think this will do any good.", japanese: 'これは何の益にもならないと思います。', category_id: 9 },
    { id: 543, english: 'This may do my reputation a lot of harm.', japanese: 'このことで私の評判がガタ落ちになるかもしれません。', category_id: 9 },
    { id: 544, english: "She can't do without glasses.", japanese: '彼女は眼鏡なしではやっていけません。', category_id: 9 },
    { id: 545, english: 'He seems to be doing well at his new job.', japanese: '彼は新しい仕事を順調にやっているようです。', category_id: 9 },
    { id: 546, english: 'His son is doing electronic at college.', japanese: '彼の息子は大学で電子工学を専攻しています。', category_id: 9 },
    { id: 547, english: 'What do you wanto to eat for dinner?/Anything will do.', japanese: '夕食は何を食べたいですか？/何でもいいです。', category_id: 9 },
    { id: 548, english: 'What is done cannot be undone.', japanese: '一度したことは取り返しがつきません。', category_id: 9 },
    { id: 549, english: 'Has she kept all the receipts?', japanese: '彼女はレシートを全部取ってありますか？', category_id: 10 },
    { id: 550, english: 'She is keeping something from me.', japanese: '彼女は私に何か隠しています。', category_id: 10 },
    { id: 551, english: 'Many people keep money in the bank.', japanese: 'たくさんの人は銀行にお金を預けます。', category_id: 10 },
    { id: 552, english: 'Why did he keep you after work?', japanese: 'なぜ彼は君を仕事後に残したのですか？', category_id: 10 },
    { id: 553, english: 'Can you keep a secret?', japanese: '秘密を守れますか？', category_id: 10 },
    { id: 554, english: 'She always keeps a promise.', japanese: '彼女はいつも約束を守ります。', category_id: 10 },
    { id: 555, english: 'Does his watch keep good time?', japanese: '彼の時計は正確ですか？', category_id: 10 },
    { id: 556, english: 'I keep early hours.', japanese: '私は早寝早起きです。', category_id: 10 },
    { id: 557, english: 'Would you keep this book for me until tomorrow?', japanese: 'この本を明日まで取り置いていただけますか？', category_id: 10 },
    { id: 558, english: "Don't keep company with them.", japanese: '彼らとは付き合わないで。', category_id: 10 },
    { id: 559, english: 'You should keep these documents for future use.', japanese: 'あなたは将来使うためにこれらの文書を取っておくべきです。', category_id: 10 },
    { id: 560, english: "Don't keep anything from us.", japanese: '私たちに何も隠し事をしないでください。', category_id: 10 },
    { id: 561, english: 'She keeps her money under the mattress.', japanese: '彼女はタンス貯金をしています。', category_id: 10 },
    { id: 562, english: 'What is keeping him?', japanese: '彼は何をぐずぐずしているんですか？', category_id: 10 },
    { id: 563, english: 'He can never keep a secret.', japanese: '彼は決して秘密を守れません。', category_id: 10 },
    { id: 564, english: 'I want her to keep her promise.', japanese: '私は彼女に約束を守ってもらいたいです。', category_id: 10 },
    { id: 565, english: 'This watch has been keeping good time for ten years.', japanese: 'この時計は十年間正確に時を刻んでいます。', category_id: 10 },
    { id: 566, english: 'My job makes it hard for me to keep regular hours.', japanese: '仕事のせいで私は規則正しい生活をするのが難しいです。', category_id: 10 },
    { id: 567, english: 'I asked them to keep the item.', japanese: '私は彼らにその品物を取り置いてもらうように頼みました。', category_id: 10 },
    { id: 568, english: 'While I was in Nagoya, he kindly kept me company.', japanese: '私が名古屋にいる間、彼は親切にも私の相手をしてくれました。', category_id: 10 },
    { id: 569, english: 'This meat will keep till tomorrow.', japanese: 'この肉は明日までもつでしょう。', category_id: 10 },
    { id: 570, english: 'This job will keep.', japanese: 'この仕事は後に回せます。', category_id: 10 },
    { id: 571, english: "Keep warm so that you won't catch a cold.", japanese: '風邪をひかないように暖かくしていて。', category_id: 10 },
    { id: 572, english: 'The baby kept crying for a while.', japanese: 'その赤ちゃんはしばらく泣き続けました。', category_id: 10 },
    { id: 573, english: 'I keeps my room tidy.', japanese: '私は自分の部屋をきちんとしています。', category_id: 10 },
    { id: 574, english: 'We kept the candle burning all night.', japanese: '私たちは一晩中蝋燭を灯し続けました。', category_id: 10 },
    { id: 575, english: 'He keeps from alcohol.', japanese: '彼はアルコールを控えています。', category_id: 10 },
    { id: 576, english: "He couldn't keep from yawning.", japanese: '彼女はあくびをするのを堪えられなかった。', category_id: 10 },
    { id: 577, english: 'He always keeps his son from danger.', japanese: '彼はいつも息子を危険から遠ざけます。', category_id: 10 },
    { id: 578, english: 'I could not keep her from leaving.', japanese: '私は彼女がさるのを止められませんでした。', category_id: 10 },
    { id: 579, english: 'How long will this keep?', japanese: 'これはどのくらいもちますか？', category_id: 10 },
    { id: 580, english: 'Will this job keep till tomorrow?', japanese: 'この仕事は明日に回せますか？', category_id: 10 },
    { id: 581, english: 'He told everyone to keep quiet.', japanese: '彼はみんなに静かにするように言いました。', category_id: 10 },
    { id: 582, english: 'The building kept burning for hours.', japanese: 'その建物は何時間も燃え続けました。', category_id: 10 },
    { id: 583, english: 'The noise outside kept me awake all night.', japanese: '外の騒音で私は一晩中眠れませんでした。', category_id: 10 },
    { id: 584, english: 'She told us to keep our eyes closed.', japanese: '彼女は私たちに目を閉じておくように言った。', category_id: 10 },
    { id: 585, english: 'It was hard for them to keep from drags.', japanese: '彼らに取って薬物に手を出さないことは困難でした。', category_id: 10 },
    { id: 586, english: "I couldn't keep from laughing at the sight.", japanese: '私はその光景に笑うのを抑えられませんでした。', category_id: 10 },
    { id: 587, english: 'Did the doctors keep that from the patient?', japanese: '医師たちは患者にそれを伏せたのですか？', category_id: 10 },
    { id: 588, english: 'Why did he try to keep his daughter from marrying that man.', japanese: 'なぜ彼は娘さんをあの男性と結婚させまいとしたのですか？', category_id: 10 },
    { id: 589, english: 'Keep away from the cliff!', japanese: '崖に近づかないで。', category_id: 10 },
    { id: 590, english: 'I tried to keep up in the water.', japanese: '私は水の中で浮いていようとしました。', category_id: 10 },
    { id: 591, english: 'Keep up the good work.', japanese: 'その調子で頑張ってください。', category_id: 10 },
    { id: 592, english: 'He always tries to keep up appearances.', japanese: '彼はいつも体面を保とうとします。', category_id: 10 },
    { id: 593, english: 'He tried to keep up with them.', japanese: '彼は彼らについていこうとしました。', category_id: 10 },
    { id: 594, english: 'It is hard to keep up with the times.', japanese: '時代の流れについていくのは難しいです。', category_id: 10 },
    { id: 595, english: "Keep down, or you'll be shot.", japanese: '伏せていなさい、出ないとあなたは撃たれますよ。', category_id: 10 },
    { id: 596, english: 'She told her children to keep their voices down.', japanese: '彼女は子供たちに声をあげないようにと言いました。', category_id: 10 },
    { id: 597, english: "While I was sick, I couldn't keep anything down.", japanese: '病気の間、私は食べた物を全て吐いてしまいました。', category_id: 10 },
    { id: 598, english: 'Keep to the right.', japanese: '右側通行をしなさい。', category_id: 10 },
    { id: 599, english: 'He tried to keep to the schedule.', japanese: '彼はスケジュールを守ろうとしました。', category_id: 10 },
    { id: 600, english: "Let's keep to the point.", japanese: '要点を外さないようにしましょう。', category_id: 10 },
    { id: 601, english: 'The man kept the treasure to himself.', japanese: 'その男は宝物を独り占めにしました。', category_id: 10 },
    { id: 602, english: 'I tend to keep my feelings to myself.', japanese: '私は自分の感情を外に出さない傾向があります。', category_id: 10 },
    { id: 603, english: 'The police are keeping after him.', japanese: '警官は彼を追い続けています。', category_id: 10 },
    { id: 604, english: 'The teacher kept after the student to study harder.', japanese: '先生はその生徒にもっと一生懸命勉強しろとしつこく言いました。', category_id: 10 },
    { id: 605, english: 'I want you to keep away from her.', japanese: '私はあなたに彼女に近づかないでもらいたいです。', category_id: 10 },
    { id: 606, english: 'The good weather will keep up for a few days.', japanese: '数日天気はいいでしょう。', category_id: 10 },
    { id: 607, english: "Let's keep our spirits up!", japanese: '元気出していきましょう！', category_id: 10 },
    { id: 608, english: 'He does anything to keep up appearances.', japanese: '彼は対面を保つためならなんでもします。', category_id: 10 },
    { id: 609, english: "I walked so fast that he couldn't keep up with me.", japanese: '私がとても早足で歩いたので彼はついていくことができませんでした。', category_id: 10 },
    { id: 610, english: 'It was hard for me to keep up with the class.', japanese: '私にとって落ちこぼれないでいるのは難しかったです。', category_id: 10 },
    { id: 611, english: 'They kept down so that the enemies would not notice them.', japanese: '敵が彼らに気付かないように彼らは伏せていました。', category_id: 10 },
    { id: 612, english: 'How can I keep the cost down?', japanese: 'どうやったら私のコストを抑えることができるのでしょうか？', category_id: 10 },
    { id: 613, english: 'Because of the illness, that man could not keep anything down.', japanese: '病気のためにあの男性は食べ物を全部戻してしまいました。', category_id: 10 },
    { id: 614, english: 'You are supposed to keep to the left here.', japanese: 'ここでは左側通行することになっています。', category_id: 10 },
    { id: 615, english: 'This schedule has to be kept to.', japanese: 'このスケジュールは守られなければなりません。', category_id: 10 },
    { id: 616, english: 'It is important to keep to the point.', japanese: '要点を外さないようにすることが重要です。', category_id: 10 },
    { id: 617, english: "You can't keep the money to yourself.", japanese: 'あなたはそのお金を独り占めすることはできない。', category_id: 10 },
    { id: 618, english: "Let's keep this to ourselves.", japanese: 'このことは内緒にしておきましょう。', category_id: 10 },
    { id: 619, english: 'That guy has been keeping after her for some time.', japanese: 'あの男はしばらく彼女につきまとっています。', category_id: 10 },
    { id: 620, english: 'She had to keep after him to pay back the money.', japanese: '彼女は彼に金を返すようにしつこく言わなければなりませんでした。', category_id: 10 },
    { id: 621, english: 'He lets me read any book in his study.', japanese: '彼は私に自分の書斎のどの本でも読ませてくれます。', category_id: 10 },
    { id: 622, english: 'Let me go!', japanese: '離して！', category_id: 10 },
    { id: 623, english: "I wouldn't let it go at that.", japanese: '私はどうしても諦めませんでした。', category_id: 10 },
    { id: 624, english: 'Our company let many employees go because of the bad economy.', japanese: '不況のため私の会社は多くの従業員を解雇しました。', category_id: 10 },
    { id: 625, english: 'Let me know when he comes back.', japanese: '彼が帰ってきたら私に知らせてください。', category_id: 10 },


  ]

  include ActiveHash::Associations
  belongs_to :category
end
